### ISSUE TITLE
New Table in database

### ISSUE THREAD

**Issue by pena56** [solomoreal/slash-hack-2.0#3]
Mr Prime, you will need to create a new table in the  database for Share_story and share_testimony.  here are the names in the input fields for each.
share_testimony: phone, email, first_name, last_name, testimony, date.
share_story: phone, email, first_name, last_name, story, date.

**Comment by pena56** [comment]
also add testimony_id and story_id

**Comment by pena56** [comment]
the primary key for both will be the testimony_id and story_id..
also for the date .. it should be the current date the entry was made

**Comment by ikeogu** [comment]
did you later use one table for the report

**Comment by pena56** [comment]
yes... i used 1 table for report.. jst pushed it online.

**Comment by ikeogu** [comment]
the database is not working on mine , if i pull

**Comment by ikeogu** [comment]
can you send me the reporter's table to me via email

**Comment by ikeogu** [comment]
A fully developed application need to have a solid backend for data storage
like SQL, SharePoint etc. since its online, is it accepted to show only the
proto type of it? Yes it's absolutely fine to submit just the prototype. If
you use any database like MySQL or PostgresSQL you can also submit a
database dump along with your submission. However you are allowed to submit
just the prototype
